# Generated by Django 4.0.3 on 2022-04-27 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0003_remove_user_email_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='placements',
            field=models.IntegerField(default=0),
        ),
    ]
