# Generated by Django 4.0.3 on 2022-04-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0005_alter_user_placements'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foster_parent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='foster_siblings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
