# Generated by Django 4.0.3 on 2022-04-27 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0006_user_foster_parent_user_foster_siblings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='foster_parent',
            new_name='foster_parents',
        ),
    ]
