# Generated by Django 4.0.3 on 2022-04-12 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='test_field',
            field=models.CharField(max_length=155, null=True),
        ),
    ]
