# Generated by Django 4.0.3 on 2022-04-20 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placements_api', '0010_alter_fosterparent_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='FosterSibling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('placement', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='placements_api.placement')),
            ],
        ),
    ]
