# Generated by Django 4.0.3 on 2022-04-22 20:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('placements_api', '0012_alter_fosterparent_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fostersibling',
            name='last_name',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=55),
            preserve_default=False,
        ),
    ]
